### PR TITLE
1.8.9 Port

### PR DESCRIPTION
**Pull request by shedaniel**
Check it out!

### CODE REVIEW

**Comment by shedaniel** [comment]
Please port it TeNNoX

**Comment by shedaniel** [comment]
I have updated it to support 1.9-1.10.2 tho...

**Comment by shedaniel** [comment]
Can I possibly get your permission on releasing the ported mods (1.8.9 and above)?

Thanks,
Daniel She

**Comment by tennox** [comment]
Sorry for the delay. You are allowed to distribute my mods - I don't have a big problem with it.
The only issue I would like to circumvent is the fragmentation of changes and download places, so I do ask you to try to develop in the same repository as me:
I added you as developer in the Gitlab project (and pulled your Merge request there):
https://gitlab.com/tennox-mods/CustomSelectionBox/merge_requests/1

I will try to set up an automatic deploy pipeline that would build on tagged commits and push them to the [download page](http://mods-dl.tennoxlab.de/). So you can develop independently of my approval, but the code and downloads are in one space.
I will try to support developement and maintenance as far as I can.

Do you like the idea?

**Comment by shedaniel** [comment]
Yes, it is okay. Tho I won't develop the 1.13.2 / 1.14 version on it as I rewrote the whole thing.

**Comment by tennox** [comment]
fair enough :P

**Comment by tennox** [comment]
What are your plans?

**Pull request closed without merging**
